### ISSUE TITLE
Leading zeros

### ISSUE THREAD

**Issue by kbrtrm** [kbrtrm/xword.io#8]
Would it be possible to add leading zeros to wordPosDict keys for row numbers less than 10? To create the clue lists I'm running a pretty primitive sort on wordPosDict to put them in order by their key values, and without leading zeros it sorts rows 10 and beyond out of order. Let me know if this is stupid. :)

01A-H, 02A-H, ... 10A-H, 11A-H

<img width="211" alt="screen shot 2017-02-21 at 7 17 12 pm" src="https://cloud.githubusercontent.com/assets/5074848/23192712/9ad00634-f86a-11e6-86f0-a0447cf310b4.png">

This would also help us manage even larger boards. Right now, with this system, our maxsize board is probably 26 x 26 (00 - 26 rows, A - Z cols). 26 is pretty darn big. I can also adjust the CSS to account for up to potentially 26 x 26 cell boards.

Wondering if we switched to double number system we could have unlimited board sizes? Or perhaps a 99 cell limit (this seems so out of this world, never-going-to-happen, but hey who knows)
[rr][cc]-[dir]
3344-H (row 33, column 44, horiz on a _huge_ board... I think 01A is fine... 26 is darn big, too)

**Comment by thmsdnnr** [comment]
The double number system is definitely more flexible. Would it be
zero-padded for both row and column? Also, for your sorting, does it mess
it up to have hyphen-delimiters? So RR-CC-DIR, like 33-44-H? That makes it
easier to create the key from the ROW and COL values as well as to
.split("-") it.

We totally can do this, but it will break the old boards we have, so I
could drop that table from the server db if you want and start fresh if you
don't want all the existing boards to error out when you try to click on
them. OR, if you have a little time to wait (and just don't use the old
boards and make new ones) I could figure out how to do a data migration,
which probably wouldn't be bad practice since there will likely be other
occasions when we want to change up a schema but not totally drop a table
haha: https://github.com/balmasi/migrate-mongoose

For instance, this:
```javascript
function letNumToIndex(letNum) { //gives starting index in 2D array to draw
word
  let split = letNum.split("");
  let letter, number, index;
  number = letNum.match(/\d/gi).join(""); //return just the numbers e.g.,
11A -> returns 11
  letter = letNum.match(/[A-Z]/gi).join(""); //return just the letter e.g.,
11A -> returns 'A'
  index = [(letter.charCodeAt()-65),number-1]; //convert 'A' to 0
  return index;
}
```
would just get changed to (the much cleaner!):

```javascript
function codeToArrayIndex(code) { //gives starting index in 2D array to
draw word
  let split = code.split("-");
  let row=parseInt(split[0])-1; // minus 1 as our array is zero-indexed but
our code starts at 1
  let col=parseInt(split[1])-1; // parseInt since the zero padded number
will be a string
  return [row, col];
}
```

**Comment by thmsdnnr** [comment]
Aw man, e-mail replies don't support Markdown :( 

The double number system is definitely more flexible. Would it be
zero-padded for both row and column? Also, for your sorting, does it mess
it up to have hyphen-delimiters? So RR-CC-DIR, like 33-44-H? That makes it
easier to create the key from the ROW and COL values as well as to
.split("-") it.

We totally can do this, but it will break the old boards we have, so I
could drop that table from the server db if you want and start fresh if you
don't want all the existing boards to error out when you try to click on
them. OR, if you have a little time to wait (and just don't use the old
boards and make new ones) I could figure out how to do a data migration,
which probably wouldn't be bad practice since there will likely be other
occasions when we want to change up a schema but not totally drop a table
haha: https://github.com/balmasi/migrate-mongoose

For instance, this:
```javascript
function letNumToIndex(letNum) { //gives starting index in 2D array to draw word
  let split = letNum.split("");
  let letter, number, index;
  number = letNum.match(/\d/gi).join(""); //return just the numbers e.g., 11A -> returns 11
  letter = letNum.match(/[A-Z]/gi).join(""); //return just the letter e.g., 11A -> returns 'A'
  index = [(letter.charCodeAt()-65),number-1]; //convert 'A' to 0
  return index;
}
```
would just get changed to (the much cleaner!):

```javascript
function codeToArrayIndex(code) { //gives starting index in 2D array to draw word
  let split = code.split("-");
  let row=parseInt(split[0])-1; // minus 1 as our array is zero-indexed but our code starts at 1
  let col=parseInt(split[1])-1; // parseInt since the zero padded number will be a string
  return [row, col];
}
```

**Comment by kbrtrm** [comment]
Huzzah! Very clean.

If you want to try your hand at a migration, go for it. Otherwise, I'm not really attached to any boards, destruction is fine.

**Comment by thmsdnnr** [comment]
Cool. I'm working on this locally. There's a subtle bug somewhere that the
change introduced but I should have it pushed tomorrow morning.

**Comment by thmsdnnr** [comment]
Or now! :1st_place_medal:
